# Generated by Django 5.1.3 on 2024-11-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OyKullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adresi', models.GenericIPAddressField()),
                ('oy_kullanma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketler.soru')),
            ],
            options={
                'verbose_name': 'Oy Kullanan',
                'verbose_name_plural': 'Oy Kullananlar',
                'unique_together': {('soru', 'ip_adresi')},
            },
        ),
    ]
