# Generated by Django 5.1.3 on 2024-11-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketler', '0002_oykullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='secenek',
            name='soru',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketler.question')),
            ],
        ),
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketler.question')),
            ],
            options={
                'verbose_name': 'Vote User',
                'verbose_name_plural': 'Vote Users',
                'unique_together': {('question', 'ip_address')},
            },
        ),
        migrations.DeleteModel(
            name='OyKullanici',
        ),
        migrations.DeleteModel(
            name='Secenek',
        ),
        migrations.DeleteModel(
            name='Soru',
        ),
    ]
